name: ZAP Scan

on:
  pull_request: # discuss where we actually want this running
    branches: [ "main" ]
    types: [ opened, synchronize ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "-d"

      - name: Wait for App to Start # needed?
        run: sleep 20

# https://github.com/zaproxy/action-full-scan
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
            target: 'https://www.zaproxy.org/'

#      - name: Upload ZAP Report
#        if: always()                      # Ensure the report is always uploaded
#        uses: actions/upload-artifact@v3
#        with:
#          name: zap-report
#          path: /zap/wrk/*.html           # Adjust to match where the report is saved
