name: ZAP Scan

on:
  push:
    branches: [ main ]
  pull_request: # REMOVE THE PR BIT
    branches: [ "main" ]
    types: [ opened, synchronize ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "-d"

      - name: Wait for App to Start # needed?
        run: sleep 20
# LOOKING AT ADDING TO THE PIPELINE - BUT LOOKS LIKE WE NEED SOME SETUP FIRST?
      # https://www.zaproxy.org/docs/automate/automation-framework/
      # https://www.zaproxy.org/getting-started/

# https://github.com/marketplace/actions/zap-automation-framework-scan
#      https://github.com/marketplace?query=zap&verification=verified_creator
      - name: ZAP Scan
        uses: zaproxy/action-af@v0.1.0
        with:
          plan: 'zap/plan.yml'
          cmd_options: "-config proxy.port=8081"
        env:
          ZAP_PORT: 8081  # Custom port for ZAP