name: Deploy Infrastructure with Terraform

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "terraform/**"
  push:
    branches:
      - SCRUM-73
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.3

      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "AWS credentials are set"
          
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform -chdir=terraform init #-backend-config=backend_config/dev.conf
      
      - name: Terraform Workspace Select
        run: |
          terraform workspace select -or-create dev

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Plan
        run: |
          terraform import aws_ecr_repository.activity_tracking mla-fitness-app-activity-tracking
          terraform import aws_ecr_repository.analytics_v2 mla-fitness-app-analytics-v2
          terraform import aws_ecr_repository.authservice mla-fitness-app-authservice
          terraform import aws_ecr_repository.frontend mla-fitness-app-frontend
          terraform import aws_ecr_repository.ai_service mla-fitness-app-ai-service

          terraform import aws_ecr_repository_image.activity_tracking.latest mla-fitness-app-activity-tracking:latest
          terraform import aws_ecr_repository_image.analytics_v2.latest mla-fitness-app-analytics-v2:latest
          terraform import aws_ecr_repository_image.authservice.latest mla-fitness-app-authservice:latest
          terraform import aws_ecr_repository_image.frontend.latest mla-fitness-app-frontend:latest
          terraform import aws_ecr_repository_image.ai_service.latest mla-fitness-app-ai-service:latest
          
          terraform -chdir=terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve tfplan


        