name: Pull Request build and test

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build all containers
        run: docker-compose up --build

      - name: Run tests
        run: |
          cd e2e_testing
          mvn test

      - name: Stop and clean up containers
        run: docker-compose down

