name: Unit tests
on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]

jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci --legacy-peer-deps
      - run: npm run test

  run-activity-tracking-api-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./activity-tracking
    # Docker image with Cypress pre-installed
    # https://github.com/cypress-io/cypress-docker-images/tree/master/included
    container: cypress/included:13.17.0
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - name: Start backend server
        run: npm run start:server
        env:
          NODE_ENV: test

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:5300/exercises

      - run: cypress run
